### ISSUE TITLE
I can help with the publishing if you need it 👍 

### ISSUE THREAD

**Issue by virejdasani** [ceoshikhar/better-github#4]
I already have a developer account in the chrome webstore so I can publish this one on my account for you, of course, I would give you all the credits. Let me know if you're interested.
You can check out my extension on the store here:
https://virejdasani.github.io/virej/software/extensions

**Comment by ceoshikhar** [comment]
I really appreciate it, but for right now I will have to say no. Thanks for the offer again 👍🏽

**Comment by virejdasani** [comment]
No worries mate 👍
