### ISSUE TITLE
How did you make this GIF ? the zoom effect 

### ISSUE THREAD

**Issue by aahnik** [ceoshikhar/better-github#7]
https://github.com/ceoshikhar/better-github#demo
![img](https://raw.githubusercontent.com/ceoshikhar/better-github/main/assets/demo.gif)

**Comment by ceoshikhar** [comment]
Added the zooming effect using `Sony Vegas Pro 15` and then converted the rendered video to GIF.

**Comment by ceoshikhar** [comment]
Closing the issue hoping your question was answered.
